#名子
name: 构建 PuTTY-CN

#触发条件
on: 
  watch: 
    types: [started]

#流程
jobs: 
  build: 
    name: 构建 PuTTY-CN
    runs-on: ubuntu-latest

    steps: 
    - name: Git 项目
      run: |
        git clone https://github.com/larryli/PuTTY.git ~/PuTTY
        cd ~/PuTTY/windows
        ls -a 
    - name: 初始化Python环境
      run: |
        apt update
        apt install python
        pip install argparse os tempfile shutil subprocess pipes
    - name: 构建
      run: |
        python ./msiplatform.py
        ls -a
