#名子
name: 构建 PuTTY-CN

#触发条件
on: 
  watch: 
    types: [started]

#流程
jobs: 
  build: 
    name: 初始化系统
    runs-on: ubuntu-latest

    steps: 
    - name: Git 项目
      run: |
        git clone https://github.com/larryli/PuTTY.git ~/PuTTY
        cd ~/PuTTY/windows
        ls -a 
    - name: 构建
      run: |
        make -f Makefile.mgw CC=winegcc RC=wrc
        ls -a
