#名子
name: 构建 PuTTY-CN

#触发条件
on: 
  watch: 
    types: [started]

#流程
jobs: 
  build: 
    name: 构建 PuTTY-CN
    runs-on: ubuntu-latest

    steps: 
    - name: Git 项目
      run: |
        git clone -b master https://github.com/larryli/PuTTY.git ~/PuTTY
        cd ~/PuTTY/windows
        ls -a 
    - name: 初始化Python环境
      run: |
        sudo apt update
        sudo apt -y install python
        sudo pip --version
    - name: 构建
      run: |
        sudo python ~/PuTTY/windows/msiplatform.py
        ls -a
