#名子
name: neofetch

#触发条件
on: 
  watch: 
    types: [started]

#流程
jobs: 
  build: 
    name: neofetch
    runs-on: ubuntu-latest

    steps: 
    - name: 下载项目文件
      run: |
        sudo apt update
        sudo apt install neofetch
        sudo neofetch
