#名子
name: 构建 PuTTY-CN

#触发条件
on: 
  watch: 
    types: [started]

#流程
jobs: 
  build: 
    name: 构建 PuTTY-CN
    runs-on: ubuntu-latest

    steps: 
    - name: 下载项目文件
      run: |
      apt update
        apt install neofetch
        nofetch
