name: 编译OrangeFox Recovery

on:
  watch:
    types: [started]
    
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Prepare the build environment
        run: |
          cd ~
          sudo apt install git aria2 -y
          git clone https://gitlab.com/OrangeFox/misc/scripts
          cd scripts
          sudo bash setup/android_build_env.sh
          sudo bash setup/install_android_sdk.sh
      # Runs a single command using the runners shell
      - name: Sync OrangeFox sources (devices without dynamic partitions only)
        run: |
          mkdir ~/OrangeFox
          cd ~/OrangeFox
          repo init -u https://gitlab.com/OrangeFox/Manifest.git -b fox_9.0
          repo sync -j8 --force-sync
      
      
      - name: list files
        run: |
          cd ~
          ls -a
