# 20250708：使用DeepSeek R1 0528 优化配置结构；由于Coding平台即将下线，新增cnb平台。

name: Sync To Gitee and Coding (ScoopInstaller)
on: 
  watch: 
    types: [started]
  schedule: 
    - cron: "0 19 * * *"

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: 
          - name: 'Gitee'
            key: ${{ secrets.GITEE_PRIVATE_KEY }}
            repo_domain: 'gitee.com'
            base_url: 'ScoopInstaller_Mirrors'
            
          - name: 'Coding'
            key: ${{ secrets.CODING_PRIVATE_KEY }}
            repo_domain: 'e.coding.net/huiaei'
            base_url: 'ScoopInstaller_Mirrors'
          
          - name: 'cnb'
            key: ${{ secrets.CNB_PRIVATE_KEY }}
            repo_domain: 'cnb.cool'
            base_url: 'ScoopInstaller_Mirrors'

      # 主仓库列表
      include:
        - repo_set: 
          - { src: "git@github.com:ScoopInstaller/Scoop.git" }
          - { src: "git@github.com:ScoopInstaller/Main.git" }
          - { src: "git@github.com:ScoopInstaller/Extras.git" }
          - { src: "git@github.com:ScoopInstaller/Versions.git" }
          - { src: "git@github.com:ScoopInstaller/Nirsoft.git" }
          - { src: "git@github.com:ScoopInstaller/PHP.git" }
          - { src: "git@github.com:ScoopInstaller/Nonportable.git" }
          - { src: "git@github.com:ScoopInstaller/Java.git" }
          - { src: "git@github.com:ScoopInstaller/Tests.git" }

        # 第三方仓库特殊处理
        - repo_set:
          - src: "git@github.com:Calinou/scoop-games.git"
            dest: "Games.git"
          - src: "git@github.com:niheaven/scoop-sysinternals.git" 
            dest: "Sysinternals.git"
          - src: "git@github.com:matthewjberger/scoop-nerd-fonts.git"
            dest: "Nerd-fonts.git"

    steps:
      - name: Sync ${{ matrix.platform.name }} repositories
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ matrix.platform.key }}
        with:
          source-repo: ${{ format('{0}', repo.src) }}
          destination-repo: |
            git@${{ matrix.platform.repo_domain }}:${{ matrix.platform.base_url }}/${
              { 
                repo.dest || split(repo.src, '/')[1] | replace('.git', '')
              }
            }.git
