# 20250708：使用AI优化配置结构；由于Coding平台即将下线，新增cnb平台。


name: Git-Sync (ScoopInstaller)
on: 
  watch: 
    types: [started]
  schedule: 
    - cron: "0 19 * * *"

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - name: 'Gitee'
            key: ${{ secrets.GITEE_PRIVATE_KEY }}
            repo_domain: 'gitee.com'
            base_url: 'ScoopInstaller_Mirrors'
          - name: 'Coding'
            key: ${{ secrets.CODING_PRIVATE_KEY }}
            repo_domain: 'e.coding.net/huiaei'
            base_url: 'ScoopInstaller_Mirrors'
          - name: 'cnb'
            key: ${{ secrets.CNB_PRIVATE_KEY }}
            repo_domain: 'cnb.cool'
            base_url: 'ScoopInstaller_Mirrors'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ matrix.platform.key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ matrix.platform.repo_domain }} >> ~/.ssh/known_hosts

      - name: Sync main repositories
        env:
          REPO_DOMAIN: ${{ matrix.platform.repo_domain }}
          BASE_URL: ${{ matrix.platform.base_url }}
        run: |
          repos=(
            "ScoopInstaller/Scoop"
            "ScoopInstaller/Main"
            "ScoopInstaller/Extras"
            "ScoopInstaller/Versions"
            "ScoopInstaller/Nirsoft"
            "ScoopInstaller/PHP"
            "ScoopInstaller/Nonportable"
            "ScoopInstaller/Java"
            "ScoopInstaller/Tests"
          )
          for repo in "${repos[@]}"; do
            src="git@github.com:${repo}.git"
            dest_name=$(basename "$repo")
            dest="git@${REPO_DOMAIN}:${BASE_URL}/${dest_name}.git"
            echo "Syncing $src to $dest"
            docker run --rm \
              -e SSH_PRIVATE_KEY="$(cat ~/.ssh/id_rsa)" \
              wearerequired/git-mirror "$src" "$dest"
          done

      - name: Sync third-party repositories
        env:
          REPO_DOMAIN: ${{ matrix.platform.repo_domain }}
          BASE_URL: ${{ matrix.platform.base_url }}
        run: |
          declare -A repos=(
            ["git@github.com:Calinou/scoop-games.git"]="Games.git"
            ["git@github.com:niheaven/scoop-sysinternals.git"]="Sysinternals.git"
            ["git@github.com:matthewjberger/scoop-nerd-fonts.git"]="Nerd-fonts.git"
          )
          for src in "${!repos[@]}"; do
            dest="git@${REPO_DOMAIN}:${BASE_URL}/${repos[$src]}"
            echo "Syncing $src to $dest"
            docker run --rm \
              -e SSH_PRIVATE_KEY="$(cat ~/.ssh/id_rsa)" \
              wearerequired/git-mirror "$src" "$dest"
          done
            
