# 工作流名称
name: Git Sync (ScoopInstaller)

# 触发条件
on: 
  # 当有人Star此仓库时触发（用于手动触发）
  watch:
    types: [started]
  # 定时任务：每天 UTC 19:00 (北京时间次日 03:00) 触发
  schedule:
  - cron: "0 19 * * *"
  # 允许手动从 Actions 页面触发
  workflow_dispatch:

# 作业
jobs:
  # 定义一个名为 sync-mirrors 的作业
  sync-mirrors:
    runs-on: ubuntu-latest
    
    # 使用 strategy.matrix 来定义变化的配置
    strategy:
      # 设置 fail-fast 为 false，这样即使一个镜像同步失败，其他镜像也会继续
      fail-fast: false
      matrix:
        # -----------------------------------------------------
        # 配置区：未来只需在此处添加平台和仓库
        # -----------------------------------------------------

        # 1. 定义目标平台
        # 每个平台需要: name (显示名称), dest_base (目标URL前缀), secret_name (用于认证的私钥的名称)
        platform:
          # 已修正: 将 'secret' 改为 'secret_name'，并使用纯字符串作为值
          - name: Gitee
            dest_base: 'git@gitee.com:ScoopInstaller_Mirrors/'
            secret_name: 'GITEE_PRIVATE_KEY'
          - name: Coding
            dest_base: 'git@e.coding.net:huiaei/ScoopInstaller_Mirrors/'
            secret_name: 'CODING_PRIVATE_KEY'
          - name: CNB
            # 注意: 如果 CNB 平台使用 SSH 推送，URL 格式可能需要是 git@...
            # 如果是 HTTPS 推送，git-mirror-action 可能需要不同的认证方式 (如 token)
            dest_base: 'https://cnb.cool/ScoopInstaller_Mirrors/' 
            secret_name: 'CNB_PRIVATE_KEY'
        
        # 2. 定义需要同步的仓库
        # 每个仓库需要: name (源仓库名), org (源仓库所属的组织/用户)
        # 如果目标仓库名与源仓库名不同, 可以额外添加 dest_name 字段
        repo:
          - { name: Scoop, org: ScoopInstaller }
          - { name: Main, org: ScoopInstaller }
          - { name: Extras, org: ScoopInstaller }
          - { name: Versions, org: ScoopInstaller }
          - { name: Nirsoft, org: ScoopInstaller }
          - { name: PHP, org: ScoopInstaller }
          - { name: Nonportable, org: ScoopInstaller }
          - { name: Java, org: ScoopInstaller }
          - { name: Tests, org: ScoopInstaller }
          - { name: scoop-games, org: Calinou, dest_name: Games }
          - { name: scoop-sysinternals, org: niheaven, dest_name: Sysinternals }
          - { name: scoop-nerd-fonts, org: matthewjberger, dest_name: 'Nerd-fonts' }

    # 作业步骤
    steps:
      # 这是一个通用的同步步骤，它会为 matrix 中定义的每个组合运行一次
      - name: Sync ${{ matrix.repo.org }}/${{ matrix.repo.name }} to ${{ matrix.platform.name }}
        # 最佳实践: 建议使用具体的版本号（如 v5）而非 master，以保证稳定性
        uses: wearerequired/git-mirror-action@v5 
        env:
          # 已修正: 使用 matrix 中的 secret_name 作为 key，动态地从 secrets 上下文中查找私钥
          SSH_PRIVATE_KEY: ${{ secrets[matrix.platform.secret_name] }}
        with:
          # 动态构建源仓库 URL
          source-repo: "git@github.com:${{ matrix.repo.org }}/${{ matrix.repo.name }}.git"
          
          # 动态构建目标仓库 URL
          # 如果定义了 dest_name，则使用它；否则，使用源仓库的 name
          destination-repo: "${{ matrix.platform.dest_base }}${{ matrix.repo.dest_name || matrix.repo.name }}.git"
